### ISSUE TITLE
Add APOC tools to p2 Neo4J installations

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/docker-neo4j-knowledgebase#11]
- [X] KB2
- [X] PDB2

**Comment by matentzn** [comment]
@dosumis you can test this by running:

```
CALL apoc.help('apoc')
``` 

in kb.p2.

**Comment by dosumis** [comment]
Awesome!  Let me know when this is working on pdb.p2 I have some queries to try that should  => us some serious improvements in site efficiency.
