### ISSUE TITLE
Add label to http://splitgal4.janelia.org/cgi-bin/splitgal4.cgi

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/docker-neo4j-knowledgebase#2]
There is a (one) dangling entity in the current KB that breaks the pipeline 2:

```
http://splitgal4.janelia.org/cgi-bin/splitgal4.cgi
```
You can find it by executing:

```
MATCH (n)-[r]-() WHERE NOT n:Class AND NOT n:DataProperty AND NOT n:Individual AND NOT n:AnnotationProperty AND NOT n:ObjectProperty RETURN r,n
```

It would be great if someone could simply label it quickly (either Class or Individual) and create a new dump of the KB at.

```
http://data.virtualflybrain.org/archive/VFB-KB.tar.gz
```

 Looking at the other Sites:s, Individual would be the correct choice.

**Comment by Robbie1977** [comment]
it's a Site and should be Site & Individual updating now....
